Error: Unknown database 'taxi_app'
    at Packet.asError (G:\taxi_driver_node\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (G:\taxi_driver_node\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (G:\taxi_driver_node\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (G:\taxi_driver_node\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (G:\taxi_driver_node\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (G:\taxi_driver_node\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)Error: Unknown database 'taxi_app'
    at Packet.asError (G:\taxi_driver_node\node_modules\mysql2\lib\packets\packet.js:740:17)
    at ClientHandshake.execute (G:\taxi_driver_node\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (G:\taxi_driver_node\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (G:\taxi_driver_node\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (G:\taxi_driver_node\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (G:\taxi_driver_node\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)